# Generated by Django 5.0 on 2025-11-05 19:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('POLITICS', 'Politiek'), ('NATIONAL', 'Nationaal'), ('INTERNATIONAL', 'Internationaal'), ('SPORT', 'Sport'), ('OTHER', 'Overig')], help_text='Internal key for the category', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name in Dutch', max_length=50)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categorieën',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Article title', max_length=500)),
                ('summary', models.TextField(blank=True, help_text='Article summary/excerpt', null=True)),
                ('content', models.TextField(blank=True, help_text='Full article content', null=True)),
                ('link', models.URLField(help_text='Original article URL', max_length=1000)),
                ('guid', models.CharField(blank=True, db_index=True, help_text='RSS guid (unique identifier)', max_length=500, null=True, unique=True)),
                ('source_name', models.CharField(default='NOS', help_text='Source name', max_length=100)),
                ('source_feed_url', models.URLField(help_text='RSS feed URL', max_length=1000)),
                ('published_at', models.DateTimeField(help_text='Publication date from RSS')),
                ('image_url', models.URLField(blank=True, help_text='Article image URL', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Article category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikelen',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_articl_publish_62720b_idx'), models.Index(fields=['category'], name='news_articl_categor_ac462d_idx'), models.Index(fields=['title'], name='news_articl_title_dca5f8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(condition=models.Q(('guid__isnull', True)), fields=('link', 'published_at'), name='unique_link_published'),
        ),
    ]
