# Generated by Django 5.0 on 2025-11-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the ingestion started')),
                ('finished_at', models.DateTimeField(blank=True, help_text='When the ingestion finished', null=True)),
                ('fetched_count', models.IntegerField(default=0, help_text='Number of items fetched from feed')),
                ('inserted_count', models.IntegerField(default=0, help_text='Number of new articles inserted')),
                ('updated_count', models.IntegerField(default=0, help_text='Number of existing articles updated')),
                ('skipped_count', models.IntegerField(default=0, help_text='Number of articles skipped (duplicates)')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partieel'), ('FAILED', 'Mislukt')], default='SUCCESS', help_text='Status of the ingestion run', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error message if status is FAILED', null=True)),
            ],
            options={
                'verbose_name': 'Ingestie Run',
                'verbose_name_plural': 'Ingestie Runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='feed_ingest_started_4c10d2_idx'), models.Index(fields=['status'], name='feed_ingest_status_6e873b_idx')],
            },
        ),
    ]
